Traceback (most recent call last):
  File "cmd_modeller.py", line 51, in <module>
    a.make()                                     # do the actual homology modeling
  File "/home/dmarz/anaconda3/lib/python3.7/site-packages/modeller/automodel/loopmodel.py", line 37, in make
    automodel.make(self, exit_stage)
  File "/home/dmarz/anaconda3/lib/python3.7/site-packages/modeller/automodel/automodel.py", line 143, in make
    self.multiple_models(atmsel)
  File "/home/dmarz/anaconda3/lib/python3.7/site-packages/modeller/automodel/loopmodel.py", line 55, in multiple_models
    self.build_seq(filename, num)
  File "/home/dmarz/anaconda3/lib/python3.7/site-packages/modeller/automodel/loopmodel.py", line 170, in build_seq
    self.loop_restraints(atmsel, aln)
  File "/home/dmarz/anaconda3/lib/python3.7/site-packages/modeller/automodel/loopmodel.py", line 391, in loop_restraints
    self.special_restraints(aln)
  File "/nfs/home6/dmarz/pMHC_Modelling/outputs/test/5grd_query_12/MyLoop.py", line 31, in special_restraints
    rsr.add(M.forms.gaussian(group=M.physical.xy_distance,feature=M.features.distance(atoms['%s:%s:%s' %(contact_data[3], contact_data[2], contact_data[1])], atoms['%s:%s:%s' %(contact_data[8], contact_data[7], contact_data[6])]),mean=float(contact_data[10]), stdev=0.1))
  File "/home/dmarz/anaconda3/lib/python3.7/site-packages/modeller/coordinates.py", line 405, in __getitem__
    (self.offset, self.length, self.suffix))
  File "/home/dmarz/anaconda3/lib/python3.7/site-packages/modeller/util/modutil.py", line 23, in handle_seq_indx
    int_indx = lookup_func(*args)
  File "/home/dmarz/anaconda3/lib/python3.7/site-packages/modeller/coordinates.py", line 314, in _indxatm
    raise KeyError("No such atom: %s" % indx)
KeyError: 'No such atom: OXT:10:P'
slurmstepd: error: *** JOB 8320158 ON tcn1159 CANCELLED AT 2020-06-11T11:08:21 ***
slurmstepd: error: *** STEP 8320158.0 ON tcn1159 CANCELLED AT 2020-06-11T11:08:21 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
